export const types = {
    //[Login]
    GET_AUTHENTICATE_USER: 'GET_AUTHENTICATE_USER',
    GET_USER: 'GET_USER',
    AUTHENTICATE_MESSAGE: 'AUTHENTICATE_MESSAGE',
    GET_LOGOUT_USER: 'GET_LOGOUT_USER',
    
    //[Cars]
    GET_CARS: 'GET_CARS',
    GET_CATEGORIES: 'GET_CATEGORIES',
    SET_CATEGORIES: 'SET_CATEGORIES',
    SET_FILTER_CARS: 'SET_FILTER_CARS',
    LOADING_FILTER_CARS: 'LOADING_FILTER_CARS',

    //[Favorites]

    LOAD_FAVORITES: 'LOAD_FAVORITES',

  };